### ISSUE TITLE
keyboard at boot for luks authentication

### ISSUE THREAD

**Issue by stoomtop** [shvr/fedora-surface-pro-3-kernel#2]
Hi, I've just installed the new kernel 4.1.0-0.rc6.git1.999.surfacepro3.fc22.x86_64
on my surface pro and note it does not have touchcover keyboard functionality at boot  to enter my luks paraphrase to unlock my ssd fedora partition. Please can you fix this?At the moment I can only use the fedora partition at home where I have a usb keyboard that I am using to enter the luks at boot. Thanks

**Comment by lizalc** [comment]
You need to add the `hid_multitouch` module to your `/etc/dracut/dracut.conf`, in the `add_drivers+=""`. Then run `dracut -f` to rebuild the initramfs, so that module is loaded on boot like it needs to be.

Try that, and let me know if it works. If you don't want to mess with configuration files, there should be a new build available either later today or tomorrow with this kernel module built in.

**Comment by stoomtop** [comment]
Hi, that worked! Nice one.

I had no /etc/dracut/ directory, so created one with dracut.conf inside. Added just one line add_drivers+="hid_multitouch"
I also added that line to /usr/lib/dracut/dracut.conf.d/01-dist.conf , I ran dracut -f  and rebooted and I was able to put in my luks phrase.

Another problem I have is getting theoracle virtual box modules to compile, its ok on the standard kernel, but when I compile the surface kernel modules I get a bunch of errors: Can you help with this too please?

make KBUILD_VERBOSE=1 SUBDIRS=/tmp/vbox.0 SRCROOT=/tmp/vbox.0 CONFIG_MODULE_SIG= -C /usr/src/kernels/4.1.0-0.rc6.git1.999.surfacepro3.fc22.x86_64 modules
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (                \
echo >&2;                                                       \
echo >&2 "  ERROR: Kernel configuration is invalid.";           \
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";      \
echo >&2 ;                                                      \
/bin/false)
mkdir -p /tmp/vbox.0/.tmp_versions ; rm -f /tmp/vbox.0/.tmp_versions/*
make -f ./scripts/Makefile.build obj=/tmp/vbox.0
  gcc -Wp,-MD,/tmp/vbox.0/linux/.SUPDrv-linux.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/5.1.1/include -I./arch/x86/include -Iarch/x86/include/generated/uapi -Iarch/x86/include/generated  -Iinclude -I./arch/x86/include/uapi -Iarch/x86/include/generated/
uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -m64 -mno-80387 -mno
-fp-ret-in-387 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFI
G_AS_AVX2=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -fn
o-omit-frame-pointer -fno-optimize-sibling-calls -fvar-tracking-assignments -g -pg -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DCC_H
AVE_ASM_GOTO -include /tmp/vbox.0/include/VBox/SUPDrvMangling.h -I/usr/src/kernels/4.1.0-0.rc6.git1.999.surfacepro3.fc22.x86_64/include -I/tmp/vbox.0/ -I/tmp/vbox.0/include -I/tmp/vbox.0/r0drv/linux -I/tmp/vbox.0/vboxdrv/ -I/tmp/vbox.0/vboxdrv/include -I/tmp/vbox.0/v
boxdrv/r0drv/linux -D__KERNEL__ -DMODULE -DRT_OS_LINUX -DIN_RING0 -DIN_RT_R0 -DIN_SUP_R0 -DVBOX -DRT_WITH_VBOX -DVBOX_WITH_HARDENING -DSUPDRV_WITH_RELEASE_LOGGER -Wno-declaration-after-statement -DCONFIG_VBOXDRV_AS_MISC -DRT_ARCH_AMD64 -DVBOX_WITH_64_BITS_GUESTS  -DM
ODULE  -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(SUPDrv_linux)"  -D"KBUILD_MODNAME=KBUILD_STR(vboxdrv)" -c -o /tmp/vbox.0/linux/SUPDrv-linux.o /tmp/vbox.0/linux/SUPDrv-linux.c
  if [ "-pg" = "-pg" ]; then if [ /tmp/vbox.0/linux/SUPDrv-linux.o != "scripts/mod/empty.o" ]; then ./scripts/recordmcount  "/tmp/vbox.0/linux/SUPDrv-linux.o"; fi; fi;
  gcc -Wp,-MD,/tmp/vbox.0/.SUPDrv.o.d  -nostdinc -isystem /usr/

**Comment by lizalc** [comment]
I'm afraid I can't help much with Virtualbox as I don't use it. I may try installing it and seeing what happens sometime later. If I do I'll report back.

Glad your original issue is fixed now. There is a new build available in COPR with the `hid_multitouch` module built in now, so the `dracut.conf` modifications should no longer be necessary.
