### ISSUE TITLE
Kernel source error when installing virtualbox modules

### ISSUE THREAD

**Issue by stoomtop** [shvr/fedora-surface-pro-3-kernel#4]
Kernel source error when installing virtualbox modules

/etc/init.d/vboxdrv setup
Stopping VirtualBox kernel modules                         [  OK  ]
Uninstalling old VirtualBox DKMS kernel modules            [  OK  ]
Removing old VirtualBox netadp kernel module               [  OK  ]
Removing old VirtualBox netflt kernel module               [  OK  ]
Removing old VirtualBox kernel module                      [  OK  ]
Trying to register the VirtualBox kernel modules using DKMSError! Bad return status for module build on kernel: 4.1.0-0.rc8.git0.9991.surfacepro3.fc22.x86_64 (x86_64)
Consult /var/lib/dkms/vboxhost/5.0.0_BETA1/build/make.log for more information.
                                                           [MISLUKT](Failed, trying without DKMS)
Recompiling VirtualBox kernel modules                      [MISLUKT](Look at /var/log/vbox-install.log to find out what went wrong)

DKMS make.log for vboxhost-5.0.0_BETA1 for kernel 4.1.0-0.rc8.git0.9991.surfacepro3.fc22.x86_64 (x86_64)
Mon 22 Jun 00:34:00 CEST 2015
make: Map '/usr/src/kernels/4.1.0-0.rc8.git0.9991.surfacepro3.fc22.x86_64' wordt binnengegaan
  LD      /var/lib/dkms/vboxhost/5.0.0_BETA1/build/built-in.o
  LD      /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/built-in.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/linux/SUPDrv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/SUPDrv.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/SUPDrvGip.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/SUPDrvSem.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/SUPDrvTracer.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/SUPLibAll.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/alloc-r0drv.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/initterm-r0drv.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/memobj-r0drv.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/mpnotification-r0drv.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/powernotification-r0drv.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/linux/assert-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/linux/alloc-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/linux/initterm-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/linux/memobj-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/linux/memuserkernel-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/linux/mp-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/linux/mpnotification-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/linux/process-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/linux/semevent-r0drv-linux.o
CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/linux/semeventmulti-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/linux/semfastmutex-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/linux/semmutex-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/linux/spinlock-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/linux/thread-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/linux/thread2-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/linux/threadctxhooks-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/linux/time-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/linux/timer-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/generic/semspinmutex-r0drv-generic.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/alloc/alloc.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/checksum/crc32.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/checksum/ipv4.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/checksum/ipv6.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/err/RTErrConvertFromErrno.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/err/RTErrConvertToErrno.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/log/log.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/log/logellipsis.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/log/logrel.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/log/logrelellipsis.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/log/logcom.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/log/logformat.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/misc/RTAssertMsg1Weak.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/misc/RTAssertMsg2.o
 CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/misc/RTAssertMsg2AddWeak.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/misc/RTAssertMsg2AddWeakV.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/misc/RTAssertMsg2Weak.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/misc/RTAssertMsg2WeakV.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/misc/assert.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/misc/handletable.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/misc/handletablectx.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/misc/thread.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/string/RTStrCopy.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/string/RTStrCopyEx.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/string/RTStrCopyP.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/string/RTStrNCmp.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/string/RTStrNLen.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/string/stringalloc.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/string/strformat.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/string/strformatrt.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/string/strformattype.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/string/strprintf.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/string/strtonum.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/table/avlpv.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/time/time.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/r0drv/linux/RTLogWriteDebugger-r0drv-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/generic/RTAssertShouldPanic-generic.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/generic/RTLogWriteStdErr-stub-generic.o
 CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/generic/RTLogWriteStdOut-stub-generic.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/generic/RTLogWriteUser-generic.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/generic/RTMpGetArraySize-generic.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/generic/RTMpGetCoreCount-generic.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/generic/RTSemEventWait-2-ex-generic.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/generic/RTSemEventWaitNoResume-2-ex-generic.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/generic/RTSemEventMultiWait-2-ex-generic.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/generic/RTSemEventMultiWaitNoResume-2-ex-generic.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/generic/RTTimerCreate-generic.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/generic/errvars-generic.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/generic/mppresent-generic.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/generic/uuid-generic.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/VBox/log-vbox.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/common/alloc/heapsimple.o
  LD [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxdrv/vboxdrv.o
  LD      /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxnetadp/built-in.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxnetadp/linux/VBoxNetAdp-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxnetadp/VBoxNetAdp.o
  LD [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxnetadp/vboxnetadp.o
  LD      /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxnetflt/built-in.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxnetflt/linux/VBoxNetFlt-linux.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxnetflt/VBoxNetFlt.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxnetflt/SUPR0IdcClient.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxnetflt/SUPR0IdcClientComponent.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxnetflt/linux/SUPR0IdcClient-linux.o
CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxnetflt/linux/SUPR0IdcClient-linux.o
  LD [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxnetflt/vboxnetflt.o
  LD      /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxpci/built-in.o
  CC [M]  /var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxpci/linux/VBoxPci-linux.o
/var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxpci/linux/VBoxPci-linux.c: In functie ‘vboxPciOsDevRegisterIrqHandler’:
/var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxpci/linux/VBoxPci-linux.c:927:22: fout: ‘IRQF_DISABLED’ undeclared (first use in this function)
                      IRQF_DISABLED, /\* keep irqs disabled when calling the action handler _/
                      ^
/var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxpci/linux/VBoxPci-linux.c:927:22: note: each undeclared identifier is reported only once for each function it appears in
scripts/Makefile.build:258: recept voor doel '/var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxpci/linux/VBoxPci-linux.o' is mislukt
make[2]: *_\* [/var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxpci/linux/VBoxPci-linux.o] Fout 1
scripts/Makefile.build:403: recept voor doel '/var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxpci' is mislukt
make[1]: **\* [/var/lib/dkms/vboxhost/5.0.0_BETA1/build/vboxpci] Fout 2
Makefile:1387: recept voor doel '_module_/var/lib/dkms/vboxhost/5.0.0_BETA1/build' is mislukt
make: **\* [_module_/var/lib/dkms/vboxhost/5.0.0_BETA1/build] Fout 2
make: Map '/usr/src/kernels/4.1.0-0.rc8.git0.9991.surfacepro3.fc22.x86_64' wordt verlaten

**Comment by lizalc** [comment]
I can't reproduce this. I've used 4.3.28 from both the Oracle provided repo and `.run` as well as the 5.0.0-rc1 `.run`. In all cases the modules built successfully. However they are not signed by default so will fail to load with Secure Boot enabled.

**Comment by lizalc** [comment]
You will also need to disable Secure Boot to correctly register the modules with dkms.

**Comment by stoomtop** [comment]
Secure boot is off, I also turned off the TPM.

 $ /etc/init.d/vboxdrv setup
Stopping VirtualBox kernel modules                         [  OK  ]
Uninstalling old VirtualBox DKMS kernel modules            [  OK  ]
Removing old VirtualBox netadp kernel module               [  OK  ]
Removing old VirtualBox netflt kernel module               [  OK  ]
Removing old VirtualBox kernel module                      [  OK  ]
Trying to register the VirtualBox kernel modules using DKMSError! Bad return status for module build on kernel: 4.1.0-0.rc8.git0.9991.surfacepro3.fc22.x86_64 (x86_64)
Consult /var/lib/dkms/vboxhost/5.0.0_BETA1/build/make.log for more information.
                                                           [MISLUKT](Failed, trying without DKMS)
Recompiling VirtualBox kernel modules                      [MISLUKT]

In the logs I see:

echo >&2 "  ERROR: Kernel configuration is invalid.";           \
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";      \
echo >&2 ;                                                      \
excerpt from:
less /var/log/vbox-install.log

gcc -Wp,-MD,/tmp/vbox.0/.vboxdrv.mod.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/5.1.1/include -I./arch/x86/include -Iarch/x86/include/generated/uapi -Iarch/x86/include/generated  -Iinclude -I./arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I
./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -m64 -mno-80387 -mno-fp-ret
-in-387 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AV
X2=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -fno-omit-
frame-pointer -fno-optimize-sibling-calls -fvar-tracking-assignments -g -pg -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DCC_HAVE_ASM
_GOTO -include /tmp/vbox.0/include/VBox/SUPDrvMangling.h -I/lib/modules/4.1.0-0.rc8.git0.9991.surfacepro3.fc22.x86_64/build/include -I/tmp/vbox.0/ -I/tmp/vbox.0/include -I/tmp/vbox.0/r0drv/linux -I/tmp/vbox.0/vboxdrv/ -I/tmp/vbox.0/vboxdrv/include -I/tmp/vbox.0/vboxd
rv/r0drv/linux -D__KERNEL__ -DMODULE -DRT_OS_LINUX -DIN_RING0 -DIN_RT_R0 -DIN_SUP_R0 -DVBOX -DRT_WITH_VBOX -DVBOX_WITH_HARDENING -DSUPDRV_WITH_RELEASE_LOGGER -Wno-declaration-after-statement -DCONFIG_VBOXDRV_AS_MISC -DRT_ARCH_AMD64 -DVBOX_WITH_64_BITS_GUESTS  -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(vboxdrv.mod)"  -D"KBUILD_MODNAME=KBUILD_STR(vboxdrv)" -DMODULE  -c -o /tmp/vbox.0/vboxdrv.mod.o /tmp/vbox.0/vboxdrv.mod.c
  ld -r -m elf_x86_64 -T ./scripts/module-common.lds --build-id  -o /tmp/vbox.0/vboxdrv.ko /tmp/vbox.0/vboxdrv.o /tmp/vbox.0/vboxdrv.mod.o
make KBUILD_VERBOSE=1 SUBDIRS=/tmp/vbox.0 SRCROOT=/tmp/vbox.0 CONFIG_MODULE_SIG= -C /lib/modules/4.1.0-0.rc8.git0.9991.surfacepro3.fc22.x86_64/build modules
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (                \
echo >&2;                                                       \
echo >&2 "  ERROR: Kernel configuration is invalid.";           \
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";      \
echo >&2 ;                                                      \
/bin/false)
mkdir -p /tmp/vbox.0/.tmp_versions ; rm -f /tmp/vbox.0/.tmp_versions/*
make -f ./scripts/Makefile.build obj=/tmp/vbox.0
  gcc -Wp,-MD,/tmp/vbox.0/linux/.VBoxNetFlt-linux.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/5.1.1/include -I./arch/x86/include -Iarch/x86/include/generated/uapi -Iarch/x86/include/generated  -Iinclude -I./arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig

**Comment by stoomtop** [comment]
I removed virtual box, re added the repo from oracle, did a dnf update and installed a new kernel and its all working now. Please close this out, thanks.
