### ISSUE TITLE
boot/vmlinux - invalid signature

### ISSUE THREAD

**Issue by nathaneltitane** [shvr/fedora-surface-pro-3-kernel#5]
upon enabling copr on F22 (x64) and doing a full upgrade (kernel + headers) - rebooting gives error on kernel load attempt:

error: /boot/vmlinuz-4.1.10-990.... has invalid signature
error: you need to load the kernel first

Press any key to continue...

**Comment by nathaneltitane** [comment]
> _ # dmesg | grep 'EFI: Loaded cert'
> [    1.222930] EFI: Loaded cert 'Microsoft Windows Production PCA 2011: a92902398e16c49778cd90f99e4f9ae17c55af53' linked to '.system_keyring'
> [    1.222948] EFI: Loaded cert 'Microsoft Corporation UEFI CA 2011: 13adbf4309bd82709c8cd54f316ed522988a1bd4' linked to '.system_keyring'
> [    1.223382] EFI: Loaded cert 'Fedora Secure Boot CA: fde32599c2d61db1bf5807335d7b20e4cd963b42' linked to '.system_keyring'
> _ # keyctl list %:.system_keyring
> 4 keys in keyring:
> 923715224: ---lswrv     0     0 asymmetric: Fedora kernel signing key: 2c9f977774b8d0cbbb790e0d6b20524d43fd3afb
> 1020647461: ---lswrv     0     0 asymmetric: Fedora Secure Boot CA: fde32599c2d61db1bf5807335d7b20e4cd963b42
> 763485680: ---lswrv     0     0 asymmetric: Microsoft Corporation UEFI CA 2011: 13adbf4309bd82709c8cd54f316ed522988a1bd4
> 961052172: ---lswrv     0     0 asymmetric: Microsoft Windows Production PCA 2011: a92902398e16c49778cd90f99e4f9ae17c55af53

**Comment by nathaneltitane** [comment]
Resolved. Add Red Hat key using these instructions http://jwboyer.livejournal.com/46149.html - as proposed by shvr

**Comment by lizalc** [comment]
Note for future readers: the `pesign` package will need to be installed along with following the above linked instructions.
